### ISSUE TITLE
Create issue does nothing

### ISSUE THREAD

**Issue by manwe** [mantisbt-plugins/TelegramBot#30] opened 2019-05-10 10:18 UTC
When sending text to the bot, I have two options: Create issue and add note. When choosing the first one nothing happens, no other options offered. Adding a note asks for more options.

Debug log:

{"update_id":836342763, "callback_query":{"id":"586585762160892758","from":{"id":136575140,"is_bot":false,"first_name":"Jon","last_name":"Bonilla","username":"jbmanwe","language_code":"es"},"message":{"message_id":17,"from":{"id":863583925,"is_bot":true,"first_name":"ubsoporte","username":"ubsoporte_bot"},"chat":{"id":136575140,"first_name":"Jon","last_name":"Bonilla","username":"jbmanwe","type":"private"},"date":1557483165,"reply_to_message":{"message_id":16,"from":{"id":136575140,"is_bot":false,"first_name":"Jon","last_name":"Bonilla","username":"jbmanwe","language_code":"es"},"chat":{"id":136575140,"first_name":"Jon","last_name":"Bonilla","username":"jbmanwe","type":"private"},"date":1557483165,"text":"Echen"},"text":"Select an action from:"},"chat_instance":"-3778251224232573802","data":"{\"rb\":{\"gp\":{\"id\":0,\"p\":1,\"fp\":1}}}"}}
[2019-05-10 12:13:10] bot_log.DEBUG: Verbose HTTP Request output:
* Expire in 0 ms for 6 (transfer 0x55b0b3003d30)
* Expire in 30000 ms for 8 (transfer 0x55b0b3003d30)
* Expire in 150000 ms for 2 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 1 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
* Expire in 0 ms for 1 (transfer 0x55b0b3003d30)
*   Trying 149.154.167.220...
* TCP_NODELAY set
* Expire in 15000 ms for 3 (transfer 0x55b0b3003d30)
* Expire in 200 ms for 4 (transfer 0x55b0b3003d30)
* Connected to api.telegram.org (149.154.167.220) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* NPN, negotiated HTTP1.1
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=Domain Control Validated; CN=api.telegram.org
*  start date: May  4 14:42:31 2018 GMT
*  expire date: May 23 16:17:38 2020 GMT
*  subjectAltName: host "api.telegram.org" matched cert's "api.telegram.org"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
> POST /bot863583925:AAF-2vQFFFFFFFFFFFFFFMhyubVr0/answerCallbackQuery HTTP/1.1
Host: api.telegram.org
User-Agent: GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.4-2
Content-Type: application/x-www-form-urlencoded
Content-Length: 36

* upload completely sent off: 36 out of 36 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.12.2
< Date: Fri, 10 May 2019 10:13:10 GMT
< Content-Type: application/json
< Content-Length: 25
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, OPTIONS
< Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< 
* Connection #0 to host api.telegram.org left intact

 [] []

**Comment by brlumen** [comment] 2019-05-10 13:59
Please tell us more about your configuration, namely: plugin version, php
version, mantisbt version.

пт, 10 мая 2019, 17:18 Jon Bonilla <notifications@github.com>:

**Comment by brlumen** [comment] 2019-05-10 14:24
Please note that the plugin completely repeats the logic of the web
interface mantisbt when creating tasks.  Therefore, you must make sure that
the user on whose behalf you are trying to create a task can do this from
the web interface.

пт, 10 мая 2019, 17:18 Jon Bonilla <notifications@github.com>:

**Comment by manwe** [comment] 2019-05-10 16:06
My user is administrator. I'm testing it. I do have issue creation rights. 
We're using php 7.3.4 (debian buster) and mantisbt 2.20.0
Plugin version is 1.5.0 (downloaded today)

**Comment by brlumen** [comment] 2019-05-12 03:51
Are there any error messages on the page "plugin.php? page = TelegramBot / monitor_page" ?

**Comment by manwe** [comment] 2019-05-12 08:04
> Are there any error messages on the page "plugin.php? page = TelegramBot / monitor_page" ?

None

**Comment by brlumen** [comment] 2019-05-12 09:23
Please send me your mantisbt configuration file. Clear confidential information before shipping.

**Comment by manwe** [comment] 2019-05-13 08:16
I'm receiving notifications when a note has been added or a ticket assigned. Looks good but can't create issues from telegram.

**Comment by brlumen** [comment] 2019-05-13 08:21
Can you add notes through the bot?

**Comment by manwe** [comment] 2019-05-13 08:25
El Sun, 12 May 2019 02:23:29 -0700
Grigoriy <notifications@github.com> escribió:

> Please send me your mantisbt configuration file. Clear confidential
> information before shipping.
> 

Attached.


thank you



-- 
https://pekepbx.com
https://www.issabel.com/multitenant

**Comment by manwe** [comment] 2019-05-13 08:27
> Can you add notes through the bot?

Yes, I can

**Comment by brlumen** [comment] 2019-05-13 08:29
> El Sun, 12 May 2019 02:23:29 -0700 Grigoriy <notifications@github.com> escribió:
> Please send me your mantisbt configuration file. Clear confidential information before shipping.
> Attached. thank you
> […](#)
> -- https://pekepbx.com https://www.issabel.com/multitenant

Where did you attach the file?

**Comment by manwe** [comment] 2019-05-13 08:36
ohm. I answered via email and attached the file. I thought that would work. 
Here's a link to the file:
[config file](https://www.dropbox.com/s/xahu7mtl4xsgqg7/config_inc.php?dl=0)

**Comment by brlumen** [comment] 2019-05-13 08:59
I managed to reproduce the error.
Looking for reasons for what could be the problem.

**Comment by brlumen** [comment] 2019-05-13 09:18
Most likely, in your user settings, the default project is no longer an existing project.

Please set the correct project as default.
Note that the plugin repeats the logic of mantisbt behavior and if the default project is set as a project in the user settings, not "All projects", the TelegramBot will not offer to select a project when creating an issue, but create an issue with the default project.

**Comment by brlumen** [comment] 2019-05-13 09:43
If you have only one project and on the user configuration page it seems to be selected correctly, anyway, try setting it again.
Then you need to send any text to the bot so that it can complete the process of creating an issue with a bad-draft project.
Upon completion, the bot must report that the project does not exist and then everything should work fine.

**Comment by manwe** [comment] 2019-05-13 09:47
> If you have only one project and on the user configuration page it seems to be selected correctly, anyway, try setting it again.
> Then you need to send any text to the bot so that it can complete the process of creating an issue with a bad-draft project.
> Upon completion, the bot must report that the project does not exist and then everything should work fine.

My default project is "All projects"

Changed the default to one specific project and it worked.
Changed ot another spcecific proyect which required a custom field to be filed to create the issue and failed. 

Should it work when "all projects" (Todos los projectos) is my default?

**Comment by brlumen** [comment] 2019-05-13 10:55
Of course it should work. Moreover, only in this configuration, the bot will choose a project.

Unfortunately, projects with custom fields are currently not supported.
But at this stage such a project should not affect the work of the bot.

Tell us more about your projects structure. How many of them? The depth of the hierarchy? What type of custom field are you using?

**Comment by josemaX** [comment] 2019-05-13 18:46
Hello, I have this problem, i think is the same Issue 22 i opened some time ago https://github.com/mantisbt-plugins/TelegramBot/issues/22

I receive notifications about  new issues by Mail (my user: admin) but no by TelegramBot. Then when  commented then receive Telegram notifications.

**Comment by josemaX** [comment] 2019-05-13 19:05
Well i just solved it for me with 1.5.0 this way

Manage->Manage Plugins->TelegramBot 1.5.0->[Configure Notifications]

In section  "Any user with access level"->"Administrator" place a mark for "Status changes to 'new'"

I missed that, but is very reasonable the need to place that, so you receive notifications if you are admin and new issues are submitted.

Impersonated an user and sent an issue as him, the notification arrived immediately.

Hope this helps some one

Thanks by the plugin!!!

**Comment by brlumen** [comment] 2019-05-14 01:48
@josemaX Thank you for your feedback, but unfortunately this is not related to this issue.

**Comment by brlumen** [comment] 2019-05-14 02:13
@manwe I compared your configuration file with the default configuration file for your version of mantis. It seems that you are using the configuration file version 1.2 and partly from 2.20. On my installation, I can not run a mantisbt, he swears at the base.

Could you check your installation with the minimum possible settings from the default settings?

**Comment by brlumen** [comment] 2019-05-14 04:40
I tried many options, but could not reproduce your mistake.
For further diagnostics, you will need the mantisbt log and web server logs.
The matntisbt log can be activated via the configuration parameter $g_log_level = LOG_ALL

**Comment by manwe** [comment] 2019-05-14 09:01
@brlumen At this point:
- Notifications work
- We can reply to notifications and add issues. 

This is more than enough for us and we're very happy with the plugin. Thank you very much for coding and for your support.

Regarding your other questions: We use it for customer support. We have around 300 projects and a 3 level deepth tree. Around 800 users can report but I guess few of them will use telegram. It will be mostly for our support team. 

Creating issues when you have a default project with no custom fields works. I don't think pleaople will use it for creation rather than notifications and adding quick notes. Our custom field for issue creation is usually a contact phone number (numeric field lenght 9).

We don't need anything else and we're very gratefull to you. I can do some more debugging if that helps your development.

cheers,

Jon

**Comment by brlumen** [comment] 2019-05-14 09:04
I'm glad I could help you.
If you ever find out what the problem was, tell me please.

Good luck!

**Comment by brlumen** [comment] 2019-05-14 09:11
I have a new idea. Perhaps a problem due to the number of projects. I did not limit the number of zero nesting projects, while telegrams have limitations on the number of buttons.
I will re-issue and try to check.

**Comment by brlumen** [comment] 2019-05-14 09:18
Unfortunately the version was not confirmed. 
I close this issue.

**Closed by brlumen** 2019-05-14 09:18 UTC
